manifest:
  version: 1.0

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: v4.2.0
      import:
        name-allowlist:
          - cmsis_6
          - hal_nxp
          - hal_stm32
          - hal_nordic
        # sadly, this entry needs to be relative to the workspace dir. For the case of this 
        # devcontainer it is /workspaces, thus /workspaces/deps is the place on which the dependencies are stored
        path-prefix: deps
