CONFIG_LOG=y
CONFIG_GPIO=y
CONFIG_APP_HEARTBEAT_PERIOD_MS=100

# Assignment 3 specific settings
CONFIG_ENABLE_ASSIGNMENT_3_LOGIC=n # Set to 'y' to enable the logic for Assignment 3
CONFIG_SLEEP_TIME_250_MS=y
CONFIG_LED_BRIGHTNESS=100
CONFIG_LED_FADE_DURATION=500
CONFIG_ENABLE_EXPERT_SETTINGS=y
CONFIG_ENABLE_LED_DEBUGGING=y
CONFIG_CUSTOM_BLINK_PATTERN="101110"
