CONFIG_LOG=y
# damm, I need to remember that CONFIG_ is needed for Kconfig options

# Format taken from  /workspaces/zephyr-course/build/zephyr/.config
#
# LED Subsystem
#
CONFIG_SLEEP_TIME_250_MS=y
# CONFIG_SLEEP_TIME_500_MS is not set
# CONFIG_SLEEP_TIME_1000_MS is not set
# CONFIG_SLEEP_TIME_2000_MS is not set
# CONFIG_LED_BLINKING_TIME_MILIS=250

#
# Advanced Led settings
#
CONFIG_LED_BRIGHTNESS=100
CONFIG_LED_FADE_DURATION=500
CONFIG_ENABLE_EXPERT_SETTINGS=y

CONFIG_ENABLE_LED_DEBUGGING=y
CONFIG_CUSTOM_BLINK_PATTERN="101110"
# end of Advanced Led settings
# end of LED Subsystem

CONFIG_GPIO=y